# Travis-CI Config

language: python
python:
    - "3.5"

branches:
    only:
        - master

install: pip install -r requirements.in

script: make content && make html

after_success: [ "${TRAVIS_PULL_REQUEST}" = "false" ] && make deploy || true


